### ISSUE TITLE
Dying while Earthbending wall is active causes server crash

### ISSUE THREAD

**Issue by schindlershadow** [ProjectKorra/AvatarMod#105]
Dying while Earthbending wall is active causes server crash

avatarmod-1.5.9.3
forge 2780

`
-- Head --
Thread: Server thread
Stacktrace:
	at com.crowsofwar.avatar.common.data.BendingData.get(BendingData.java:82)
	at com.crowsofwar.avatar.common.entity.data.WallBehavior$Waiting.onUpdate(WallBehavior.java:139)
	at com.crowsofwar.avatar.common.entity.data.WallBehavior$Waiting.onUpdate(WallBehavior.java:128)
	at com.crowsofwar.avatar.common.entity.EntityWallSegment.func_70071_h_(EntityWallSegment.java:193)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: avatarmod:wallsegment (com.crowsofwar.avatar.common.entity.EntityWallSegment)
	Entity ID: 143128
	Entity Name: entity.WallSegment.name
	Entity's Exact location: XXX
	Entity's Block location: World: (XXX), Chunk: (at 5,4,0 in 281,146; contains blocks XXX to XXX), Region: (8,4; contains chunks XXX, blocks XXX)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
`

Full crash report:
https://pastebin.com/raw/ea52SBWC

**Comment by FavouriteDragon** [comment]
Hecking heck I thought I fixed this.
I guess I have another thing to do when I get back :P

**Comment by FavouriteDragon** [comment]
Ok I'd appreciate more of the crash report, but I'm pretty sure I've fixed this. Will be in the next update. (I'd like the whole thing, not just the stacktrace).

**Comment by FavouriteDragon** [comment]
Ok this should be fixed, and will be in the next update.
