### ISSUE TITLE
When I join a world, It crashes within 30 seconds to 1 minute

### ISSUE THREAD

**Issue by Hydroxl** [ProjectKorra/AvatarMod#130]
When I join a world, it ends up crashing when I have the mod installed. My forge is up to date and I have everything in order but the mod just seems to be crashing my game.

I get this report when it happens. If anyone can help me it would be greatly appreciated.
---- Minecraft Crash Report ----

Time: 9/22/19 6:57 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
	at com.crowsofwar.avatar.common.util.AvatarUtils.<clinit>(AvatarUtils.java:61)
	at com.crowsofwar.avatar.common.data.BendingData.writeToNbt(BendingData.java:511)
	at com.crowsofwar.avatar.common.data.AvatarPlayerData.writePlayerDataToNBT(AvatarPlayerData.java:81)
	at com.crowsofwar.gorecore.data.PlayerData.writeToNBT(PlayerData.java:128)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:61)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:33)
	at com.crowsofwar.gorecore.util.GoreCoreNBTUtil.writeMapToNBT(GoreCoreNBTUtil.java:161)
	at com.crowsofwar.gorecore.data.WorldDataPlayers.func_189551_b(WorldDataPlayers.java:55)
	at com.crowsofwar.avatar.common.data.AvatarWorldData.func_189551_b(AvatarWorldData.java:88)
	at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:92)
	at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:78)
	at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1052)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1000)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.2
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 292339136 bytes (278 MB) / 570425344 bytes (544 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                        | Signature                                |
	|:--------- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge     | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | gorecore  | 1.12.2-0.4.5 | avatarmod-1.5.17-alpha.jar    | None                                     |
	| UCHIJAAAA | avatarmod | 1.5.17-alpha | avatarmod-1.5.17-alpha.jar    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['horseygal101'/2357, l='Avatar Survival 2.0', x=-232.82, y=77.00, z=239.87]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by FavouriteDragon** [comment]
Actually, your forge is out of date- you need to make it 2838 or higher.
I think the curseforge page is out of date if it says otherwise :P
