### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by niturovecks** [ProjectKorra/AvatarMod#151]
It seems I am loading in the world correctly, but before I have a chance to do anything, the game crashes. Not sure what the issue is, removed all my previous mods and am still having the issue. Below I'll attach my crash report:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/3/20 11:45 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
	at com.crowsofwar.avatar.common.util.AvatarUtils.<clinit>(AvatarUtils.java:61)
	at com.crowsofwar.avatar.common.data.BendingData.writeToNbt(BendingData.java:511)
	at com.crowsofwar.avatar.common.data.AvatarPlayerData.writePlayerDataToNBT(AvatarPlayerData.java:81)
	at com.crowsofwar.gorecore.data.PlayerData.writeToNBT(PlayerData.java:128)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:61)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:33)
	at com.crowsofwar.gorecore.util.GoreCoreNBTUtil.writeMapToNBT(GoreCoreNBTUtil.java:161)
	at com.crowsofwar.gorecore.data.WorldDataPlayers.func_189551_b(WorldDataPlayers.java:55)
	at com.crowsofwar.avatar.common.data.AvatarWorldData.func_189551_b(AvatarWorldData.java:88)
	at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:92)
	at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:78)
	at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1052)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1000)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 368277808 bytes (351 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 6, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State       | ID        | Version      | Source                        | Signature                                |
	|:----------- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJAAAAAA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJAAAAAA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJAAAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | forge     | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAA | gorecore  | 1.12.2-0.4.5 | avatarmod-1.5.17-alpha.jar    | None                                     |
	| UCHIJAAAAAA | avatarmod | 1.5.17-alpha | avatarmod-1.5.17-alpha.jar    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['nitroveex'/647, l='Please Work', x=104.72, y=67.00, z=262.73]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by RairisSK** [comment]
same here brother
