### ISSUE TITLE
Minecraft Server Keep Crashing

### ISSUE THREAD

**Issue by RairisSK** [ProjectKorra/AvatarMod#152]
When i created a minecraft server trough forge and hamachi to play with my friend its keep crashing, its says [18:14:18] [Server thread/WARN] [avatarmod]: [Warn/BAD_CLIENT_PACKET] Player RairisGamingSK: Unexpected data, Sent request data for a player with account 'cf88d8f4-915c-42aa-afbf-377bc9caa6f2', but that player is not in the world.
>

**Comment by RairisSK** [comment]
and then it crashes

**Comment by RairisSK** [comment]
In crash reports its says
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4.6.2020 18:04
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
	at com.crowsofwar.avatar.common.util.AvatarUtils.<clinit>(AvatarUtils.java:61)
	at com.crowsofwar.avatar.common.data.BendingData.writeToNbt(BendingData.java:511)
	at com.crowsofwar.avatar.common.data.AvatarPlayerData.writePlayerDataToNBT(AvatarPlayerData.java:81)
	at com.crowsofwar.gorecore.data.PlayerData.writeToNBT(PlayerData.java:128)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:61)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:33)
	at com.crowsofwar.gorecore.util.GoreCoreNBTUtil.writeMapToNBT(GoreCoreNBTUtil.java:161)
	at com.crowsofwar.gorecore.data.WorldDataPlayers.func_189551_b(WorldDataPlayers.java:55)
	at com.crowsofwar.avatar.common.data.AvatarWorldData.func_189551_b(AvatarWorldData.java:88)
	at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:92)
	at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:78)
	at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1053)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1001)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:407)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:688)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 809259472 bytes (771 MB) / 1037959168 bytes (989 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387-universal.jar) 
	UCHIJAAAA	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387-universal.jar) 
	UCHIJAAAA	gorecore{1.12.2-0.4.5} [GoreCore] (AVATAR MOD BITCH.jar) 
	UCHIJAAAA	avatarmod{1.5.17-alpha} [Avatar Mod: Out of the Iceberg] (AVATAR MOD BITCH.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 2 / 20; [EntityPlayerMP['RairisGamingSK'/41, l='world', x=7644,87, y=84,00, z=5600,44], EntityPlayerMP['PlayazPwnz'/42, l='world', x=7644,25, y=84,00, z=5600,11]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by TomVerpooten** [comment]
Have you tried updating your forge?

**Comment by RGSimpleton** [comment]
The mod requires 1.12.... this happens to me and I have the latest version of 1.12.

**Comment by Mahtaran** [comment]
Is your server cracked/in offline mode?

**Comment by HarryZ10** [comment]
#167 Well, I can say that for me, I'm premium and bought my account and have the same issue.

**Comment by Mahtaran** [comment]
Actually, misread the crashlog at first. You need to update Forge.
