### ISSUE TITLE
Mod crashes when launching the game

### ISSUE THREAD

**Issue by TomVerpooten** [ProjectKorra/AvatarMod#156]
I have downloaded the avatar mod, and it worked fine, but suddenly it starts crashing. Here is my crash report. I get the exact same crash report every time. And I have deleted every other mod I had installed except form avatar and it keeps crashing. I hope you can help me.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 6/8/20 5:31 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Avatar Mod: Out of the Iceberg (avatarmod)
Caused by: unacceptable code point ' ' (0x0) special characters are not allowed
in "'string'", position 0
	at com.crowsofwar.avatar.snakeyaml.reader.StreamReader.update(StreamReader.java:211)
	at com.crowsofwar.avatar.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at com.crowsofwar.avatar.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at com.crowsofwar.avatar.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at com.crowsofwar.avatar.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
	at com.crowsofwar.avatar.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
	at com.crowsofwar.avatar.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
	at com.crowsofwar.avatar.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
	at com.crowsofwar.avatar.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at com.crowsofwar.avatar.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at com.crowsofwar.avatar.snakeyaml.composer.Composer.getSingleNode(Composer.java:107)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
	at com.crowsofwar.avatar.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at com.crowsofwar.avatar.snakeyaml.Yaml.load(Yaml.java:437)
	at com.crowsofwar.gorecore.config.ConfigLoader.loadMap(ConfigLoader.java:404)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:464)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:436)
	at com.crowsofwar.avatar.common.config.ConfigStats.load(ConfigStats.java:296)
	at com.crowsofwar.avatar.AvatarMod.preInit(AvatarMod.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1010971240 bytes (964 MB) / 1300758528 bytes (1240 MB) up to 3008888832 bytes (2869 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID| Version| Source| Signature                                |
	|:----- |:------------------ |:------------------------ |:---------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2                   | minecraft.jar                            | None                                     |
	| LCH   | mcp                | 9.42                     | minecraft.jar                            | None                                     |
	| LCH   | FML                | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge              | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | gorecore           | 1.12.2-0.4.5             | avatarmod-1.5.17-alpha.jar               | None                                     |
	| LCE   | avatarmod          | 1.5.17-alpha             | avatarmod-1.5.17-alpha.jar               | None                                     |
	| LC    | crafttweaker       | 4.1.20                   | CraftTweaker2-1.12-4.1.20.574.jar        | None                                     |
	| LC    | ctgui              | 1.0.0                    | CraftTweaker2-1.12-4.1.20.574.jar        | None                                     |
	| LC    | jei                | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                | None                                     |
	| LC    | crafttweakerjei    | 2.0.3                    | CraftTweaker2-1.12-4.1.20.574.jar        | None                                     |
	| LC    | orelib             | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround          | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | elevatorid         | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar            | None                                     |
	| LC    | explorercraft      | 2.2.14                   | Explorercraft-2.2.14.jar                 | None                                     |
	| LC    | fastleafdecay      | v14                      | FastLeafDecay-v14.jar                    | None                                     |
	| LC    | gravestone         | 1.10.3                   | gravestone-1.10.3.jar                    | None                                     |
	| LC    | hardcorequesting   | @VERSION@                | HQM-1.12-5.4.0-hotfix1.jar               | None                                     |
	| LC    | llibrary           | 1.7.19                   | llibrary-1.7.19-1.12.2.jar               | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | iceandfire         | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar              | None                                     |
	| LC    | infernalmobs       | 1.7.6                    | InfernalMobs-1.12.2.jar                  | None                                     |
	| LC    | inventorytweaks    | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironbackpacks      | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar        | None                                     |
	| LC    | ironchest          | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar          | None                                     |
	| LC    | journeymap         | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar              | None                                     |
	| LC    | libraryex          | 1.1.3                    | LibraryEx-1.12.2-1.1.3.jar               | None                                     |
	| LC    | lootbags           | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar              | None                                     |
	| LC    | mob_grinding_utils | 0.3.13                   | MobGrindingUtils-0.3.13.jar              | None                                     |
	| LC    | mousetweaks        | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar            | None                                     |
	| LC    | mowziesmobs        | 1.5.5                    | mowziesmobs-1.5.5.jar                    | None                                     |
	| LC    | neat               | 1.4-17                   | Neat 1.4-17.jar                          | None                                     |
	| LC    | netherex           | 2.1.7                    | NetherEx-1.12.2-2.1.7.jar                | None                                     |
	| LC    | roguelike          | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar       | None                                     |
	| LC    | worldedit          | 6.1.10                   | worldedit-forge-mc1.12.2-6.1.10-dist.jar | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4703' Renderer: 'Intel(R) HD Graphics 4400'

**Comment by irishjoshplays** [comment]
I just begun to have the same problem. I looked over my crash report and it is pretty much the same as yours (besides different mods). I have also tried it with the single mod. Hopefully, the issue can be found and fixed soon.

**Comment by Mahtaran** [comment]
Your `<minecraft folder>/config/avatar/stats.yml` file is corrupted. Please delete it.
