### ISSUE TITLE
Crashes when in game

### ISSUE THREAD

**Issue by Stonebend** [ProjectKorra/AvatarMod#157]
When I'm in an Avatar World it crashes randomly.
Crash Report Below
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/8/20 12:18 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
	at com.crowsofwar.avatar.common.util.AvatarUtils.<clinit>(AvatarUtils.java:61)
	at com.crowsofwar.avatar.common.data.BendingData.writeToNbt(BendingData.java:511)
	at com.crowsofwar.avatar.common.data.AvatarPlayerData.writePlayerDataToNBT(AvatarPlayerData.java:81)
	at com.crowsofwar.gorecore.data.PlayerData.writeToNBT(PlayerData.java:128)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:61)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:33)
	at com.crowsofwar.gorecore.util.GoreCoreNBTUtil.writeMapToNBT(GoreCoreNBTUtil.java:161)
	at com.crowsofwar.gorecore.data.WorldDataPlayers.func_189551_b(WorldDataPlayers.java:55)
	at com.crowsofwar.avatar.common.data.AvatarWorldData.func_189551_b(AvatarWorldData.java:88)
	at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:92)
	at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:78)
	at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1053)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1001)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:407)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:688)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 575806232 bytes (549 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UCHIJAAAA	gorecore{1.12.2-0.4.5} [GoreCore] (avatarmod-1.5.17-alpha.jar) 
	UCHIJAAAA	avatarmod{1.5.17-alpha} [Avatar Mod: Out of the Iceberg] (avatarmod-1.5.17-alpha.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Stonebend'/2519, l='New World', x=163.76, y=63.78, z=220.03]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by TomVerpooten** [comment]
You need to update your forge.

**Comment by Stonebend** [comment]
I redownloaded the latest version of Forge 1.12 and it still crashes

**Comment by RGSimpleton** [comment]
Same thing happens to me they should just make it available for the newest version of forge

**Comment by Mahtaran** [comment]
This is a crash which only happens when you have an incorrect Forge version. If you still experience crashes, please open a new ticket with an updated crash report.
