### ISSUE TITLE
Crashed (Relevant information described)

### ISSUE THREAD

**Issue by HarryZ10** [ProjectKorra/AvatarMod#167]
Forge version, mod version, crash report, list of mods, and java version.

Forge Version: 1.12-14.21.1.2387 (what was available on the forge website for 1.12)

Mod Version: 1.5.17-alpha

List of Mods from the Mods view in Minecraft Client 1.12: 1) Minecraft 2) Minecraft Coder Pack 3) Forge Mod Loader 4) Minecraft Forge, 5) Mercurius_updater, 6) GoreCore, and 7) Avatar Mod: Out of the Iceberg.

Java version: Java 8 Update 251

**Comment by HarryZ10** [comment]
``---- Minecraft Crash Report ----
// You're mean.

Time: 7/8/20 6:05 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;
	at com.crowsofwar.avatar.common.util.AvatarUtils.<clinit>(AvatarUtils.java:61)
	at com.crowsofwar.avatar.common.data.BendingData.writeToNbt(BendingData.java:511)
	at com.crowsofwar.avatar.common.data.AvatarPlayerData.writePlayerDataToNBT(AvatarPlayerData.java:81)
	at com.crowsofwar.gorecore.data.PlayerData.writeToNBT(PlayerData.java:128)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:61)
	at com.crowsofwar.gorecore.data.PlayerData$1.writeV(PlayerData.java:33)
	at com.crowsofwar.gorecore.util.GoreCoreNBTUtil.writeMapToNBT(GoreCoreNBTUtil.java:161)
	at com.crowsofwar.gorecore.data.WorldDataPlayers.func_189551_b(WorldDataPlayers.java:55)
	at com.crowsofwar.avatar.common.data.AvatarWorldData.func_189551_b(AvatarWorldData.java:88)
	at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:92)
	at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:78)
	at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1053)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1001)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:407)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 585932632 bytes (558 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UCHIJAAAA	gorecore{1.12.2-0.4.5} [GoreCore] (avatarmod-1.5.17-alpha.jar) 
	UCHIJAAAA	avatarmod{1.5.17-alpha} [Avatar Mod: Out of the Iceberg] (avatarmod-1.5.17-alpha.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ImmortalYY'/1425, l='Avatar', x=-223.70, y=63.00, z=248.49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Mahtaran** [comment]
You need to update Forge.
