### ISSUE TITLE
Mod crashed entire game.

### ISSUE THREAD

**Issue by LaCohesive** [ProjectKorra/AvatarMod#186]
Upon clicking play in my launcher I was met with the typical mod loading screen and then I see this error code 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Avatar Mod: Out of the Iceberg (avatarmod)
Exit Code: -1

I have no clue what could have caused this and its aggravating because I purchased a server to play with my friends and this has halted that entirely. Please help!

**Comment by Mahtaran** [comment]
Hi! Could you attach your mod list, Forge and Java version, and the entire log (not just the crash log) from your server?

**Comment by Stone1929** [comment]
im having the same problem the only other mod that im using is twilight forest, the forge version that im using is 1.12.2 14.23.5.2854 my java version that im using is the lates one, IDK what it is. 
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 9/16/20 8:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Avatar Mod: Out of the Iceberg (avatarmod)
Caused by: unacceptable code point ' ' (0x0) special characters are not allowed
in "'string'", position 0
	at com.crowsofwar.avatar.snakeyaml.reader.StreamReader.update(StreamReader.java:211)
	at com.crowsofwar.avatar.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
	at com.crowsofwar.avatar.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
	at com.crowsofwar.avatar.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
	at com.crowsofwar.avatar.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
	at com.crowsofwar.avatar.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
	at com.crowsofwar.avatar.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
	at com.crowsofwar.avatar.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
	at com.crowsofwar.avatar.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at com.crowsofwar.avatar.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at com.crowsofwar.avatar.snakeyaml.composer.Composer.getSingleNode(Composer.java:107)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
	at com.crowsofwar.avatar.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at com.crowsofwar.avatar.snakeyaml.Yaml.load(Yaml.java:437)
	at com.crowsofwar.gorecore.config.ConfigLoader.loadMap(ConfigLoader.java:404)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:464)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:436)
	at com.crowsofwar.avatar.common.config.ConfigStats.load(ConfigStats.java:296)
	at com.crowsofwar.avatar.AvatarMod.preInit(AvatarMod.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 863940216 bytes (823 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                                        | Signature                                |
	|:----- |:-------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft      | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCH   | mcp            | 9.42         | minecraft.jar                                 | None                                     |
	| LCH   | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge          | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | gorecore       | 1.12.2-0.4.5 | avatarmod-1.5.17-alpha (1).jar                | None                                     |
	| LCE   | avatarmod      | 1.5.17-alpha | avatarmod-1.5.17-alpha (1).jar                | None                                     |
	| LC    | twilightforest | 3.11.1021    | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7262' Renderer: 'Intel(R) UHD Graphics 600'

**Comment by Mahtaran** [comment]
@Stone1929 looks like your `stats.yml` file is corrupted. Try deleting it. That, however, is another issue, if the problem persists open a new ticket for it.
