### ISSUE TITLE
Crash On Game Startup

### ISSUE THREAD

**Issue by EricDragonFire** [ProjectKorra/AvatarMod#189]
I can't even start up minecraft with this mod before it crashes mid-load. And while I do play with other mods I did attempt to load this mod by itself after deleting the config. It keeps saying "cannot use Buffers when Array Buffer Object is enabled" which I can't seem to find any solution for. My forge version is for 1.12.2 which is what curse says it's for as well. The version of forge I have for 1.12.2 is 14.23.5.2854 if anyone has any info on how to fix this problem let me know

**Comment by EricDragonFire** [comment]
Also here's my crash log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/12/20 8:16 PM
Description: Initializing game

org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(GlStateManager.java:866)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:827)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:39)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(Tessellator.java:33)
	at net.minecraft.client.Minecraft.func_180510_a(Minecraft.java:938)
	at net.minecraftforge.fml.client.SplashProgress.drawVanillaScreen(SplashProgress.java:920)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(GlStateManager.java:866)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:827)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:39)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(Tessellator.java:33)
	at net.minecraft.client.Minecraft.func_180510_a(Minecraft.java:938)
	at net.minecraftforge.fml.client.SplashProgress.drawVanillaScreen(SplashProgress.java:920)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 394486088 bytes (376 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version                  | Source                                  | Signature                                |
	|:----- |:------------------ |:------------------------ |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2                   | minecraft.jar                           | None                                     |
	| LCH   | mcp                | 9.42                     | minecraft.jar                           | None                                     |
	| LCH   | FML                | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge              | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | voxelmap           | 1.9.25                   | forgemod_VoxelMap-1.9.28_for_1.12.2.jar | None                                     |
	| LCH   | gorecore           | 1.12.2-0.4.5             | avatarmod-1.6.0-alpha.3.jar             | None                                     |
	| LCH   | avatarmod          | 1.6.0-alpha.3            | avatarmod-1.6.0-alpha.3.jar             | None                                     |
	| LCH   | backpack           | 3.0.2                    | backpack-3.0.2-1.12.2.jar               | None                                     |
	| LCH   | baubles            | 1.5.2                    | Baubles-1.12-1.5.2.jar                  | None                                     |
	| LCH   | bookshelf          | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | cfm                | 6.3.0                    | cfm-6.3.0-mc1.12.2.jar                  | None                                     |
	| LCH   | chesttransporter   | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar       | None                                     |
	| LCH   | ctm                | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar               | None                                     |
	| LCH   | jei                | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar               | None                                     |
	| LCH   | cyclicmagic        | 1.20.1                   | Cyclic-1.12.2-1.20.1.jar                | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCH   | eplus              | 5.0.179                  | EnchantingPlus-1.12.2-5.0.179.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | expandedbonemeal   | 1.2.1                    | expandedbonemeal-1.11-1.2.1.jar         | None                                     |
	| LCH   | harvest            | 1.12-1.2.7-20            | Harvest-1.12-1.2.7-20.jar               | None                                     |
	| LCH   | hatchery           | 2.2.2                    | hatchery-1.12.2-2.2.2.jar               | None                                     |
	| LCH   | infinitefluids     | 1.2.0                    | infinitefluids-1.11-1.2.0.jar           | None                                     |
	| LCH   | infinitylib        | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                  | None                                     |
	| LCH   | inventorytweaks    | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironchest          | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar         | None                                     |
	| LCH   | ironfurnaces       | 1.3.5                    | ironfurnaces-1.3.5.jar                  | None                                     |
	| LCH   | harvestcraft       | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zg.jar         | None                                     |
	| LCH   | patchouli          | 1.0-21                   | Patchouli-1.0-21.jar                    | None                                     |
	| LCH   | recipes_and_more   | 1.0.1                    | RecipesAndMore-1.12.2-1.0.1.jar         | None                                     |
	| LCH   | refinedstorage     | 1.6.15                   | refinedstorage-1.6.15.jar               | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | valkyrielib        | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar         | None                                     |
	| LCH   | simplegenerators   | 1.12.2-2.0.20.2          | simplegenerators-1.12.2-2.0.20.2.jar    | None                                     |
	| LCH   | treechopper        | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar            | None                                     |
	| LCH   | universalmodifiers | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar         | None                                     |
	| LCH   | llibrary           | 1.7.19                   | llibrary-1.7.19-1.12.2.jar              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	Patchouli open book context: n/a
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Old_Default_1.12.2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by Drillgon200** [comment]
Does the mod use vbos anywhere or use GL15.glBindBuffer anywhere without unbinding?

**Comment by EricDragonFire** [comment]
> Does the mod use vbos anywhere or use GL15.glBindBuffer anywhere without unbinding?

Idk what any of that means. Walk me through this so that I may hopefully understand and find the problem

**Comment by FavouriteDragon** [comment]
Fixed in the next update
