### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Dejuratio** [ProjectKorra/AvatarMod#190]
Forge Version: 1.12.2, 2838
Mod Version: 1.6.0 Alpha2
Mod List: JEI, JourneyMap, Optifine, Avatar Mod 2
Java Version: 261 I think

CRASH REPORT:
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Avatar Mod: Out of the Iceberg (avatarmod)
Exit Code: -1"

FULL CRASH REPORT: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 10/14/20 2:02 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Avatar Mod: Out of the Iceberg (avatarmod)
Caused by: Can't construct a java object for tag:yaml.org,2002:com.crowsofwar.avatar.common.config.ConfigClient$ActiveBendingSettings; exception=Class not found: com.crowsofwar.avatar.common.config.ConfigClient$ActiveBendingSettings
 in 'string', line 3, column 24:
    activeBendingSettings: !!com.crowsofwar.avatar.common.c ... 
                           ^

	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:314)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453)
	at com.crowsofwar.avatar.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434)
	at com.crowsofwar.avatar.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
	at com.crowsofwar.avatar.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at com.crowsofwar.avatar.snakeyaml.Yaml.load(Yaml.java:437)
	at com.crowsofwar.gorecore.config.ConfigLoader.loadMap(ConfigLoader.java:404)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:464)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:436)
	at com.crowsofwar.avatar.config.ConfigClient.load(ConfigClient.java:79)
	at com.crowsofwar.avatar.AvatarMod.preInit(AvatarMod.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.crowsofwar.avatar.snakeyaml.error.YAMLException: Class not found: com.crowsofwar.avatar.common.config.ConfigClient$ActiveBendingSettings
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:642)
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:300)
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
	... 58 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 234174480 bytes (223 MB) / 536870912 bytes (512 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_F5 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version       | Source                          | Signature                                |
	|:----- |:---------- |:------------- |:------------------------------- |:---------------------------------------- |
	| LCH   | minecraft  | 1.12.2        | minecraft.jar                   | None                                     |
	| LCH   | mcp        | 9.42          | minecraft.jar                   | None                                     |
	| LCH   | FML        | 8.0.99.99     | forge-1.12.2-14.23.5.2838.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge      | 14.23.5.2838  | forge-1.12.2-14.23.5.2838.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | gorecore   | 1.12.2-0.4.5  | avatarmod-1.6.0-alpha.2.jar     | None                                     |
	| LCE   | avatarmod  | 1.6.0-alpha.2 | avatarmod-1.6.0-alpha.2.jar     | None                                     |
	| LC    | jei        | 4.15.0.296    | jei_1.12.2-4.15.0.296 (1).jar   | None                                     |
	| LC    | journeymap | 1.12.2-5.7.1  | journeymap-1.12.2-5.7.1 (3).jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.8141' Renderer: 'Intel(R) UHD Graphics 630'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BBVanillaReborn_V1.3.1.zip
	OpenGlVersion: 4.6.0 - Build 26.20.100.8141
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 12

**Comment by FavouriteDragon** [comment]
Delete your config

**Comment by Marcosceme** [comment]
@FavouriteDragon but what is the config what i delete
