### ISSUE TITLE
Crash when trying to open Minecraft with mods !!

### ISSUE THREAD

**Issue by fransushi** [ProjectKorra/AvatarMod#191]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 10/17/20 1:58 PM
Description: Initializing game

org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(SourceFile:770)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:31)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:22)
	at net.minecraft.client.Minecraft.func_180510_a(Minecraft.java:938)
	at net.minecraftforge.fml.client.SplashProgress.drawVanillaScreen(SplashProgress.java:920)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(SourceFile:770)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:31)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:22)
	at net.minecraft.client.Minecraft.func_180510_a(Minecraft.java:938)
	at net.minecraftforge.fml.client.SplashProgress.drawVanillaScreen(SplashProgress.java:920)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.15.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 594468888 bytes (566 MB) / 805306368 bytes (768 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 7 total; -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version       | Source                        | Signature                                |
	|:----- |:--------- |:------------- |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft | 1.12.2        | minecraft.jar                 | None                                     |
	| LCH   | mcp       | 9.42          | minecraft.jar                 | None                                     |
	| LCH   | FML       | 8.0.99.99     | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge     | 14.23.5.2854  | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | gorecore  | 1.12.2-0.4.5  | avatarmod-1.6.0-alpha.4.jar   | None                                     |
	| LCH   | avatarmod | 1.6.0-alpha.4 | avatarmod-1.6.0-alpha.4.jar   | None                                     |

	Loaded coremods (and transformers): 
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.2
	OpenGL: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-14.7.8, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, file/Stay_True+1, file/Dramatic+Sky+for+1
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz

**Comment by FavouriteDragon** [comment]
Should be fixed in the next update.
