### ISSUE TITLE
Minecraft Crashes at start up (info included)

### ISSUE THREAD

**Issue by HelloitsRoFi** [ProjectKorra/AvatarMod#212]
also I know nothing about how files or code or anything works so if its anything like that that is the problem pls explain in alot of detail and easy to understand words xD

Im using forge version 1.12.2-forge-14.23.5.2854 and am using mod version 1.5.17-alpha. 
List of mods : avatarmod, betterfps, biomesoplenty, chiselandbits, cosmeticarmorreworked, creatviecore, dragonmounts2, mocreatures, fairylights, hats, ichunutil, jei, more+mobs+, morph, optifine, onlinepicframe, rex aditional structures, sparks hammers, torohealth, treechopper, and xeiros minimap.

Crash report : 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_20.27.3_Forge_1.12.jar)
  CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 1/26/21 1:04 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Avatar Mod: Out of the Iceberg (avatarmod)
Caused by: Can't construct a java object for tag:yaml.org,2002:com.crowsofwar.avatar.config.ConfigClient$ActiveBendingSettings; exception=Class not found: com.crowsofwar.avatar.config.ConfigClient$ActiveBendingSettings
 in 'string', line 3, column 24:
    activeBendingSettings: !!com.crowsofwar.avatar.config.C ... 
                           ^

	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:314)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453)
	at com.crowsofwar.avatar.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434)
	at com.crowsofwar.avatar.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
	at com.crowsofwar.avatar.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at com.crowsofwar.avatar.snakeyaml.Yaml.load(Yaml.java:437)
	at com.crowsofwar.gorecore.config.ConfigLoader.loadMap(ConfigLoader.java:404)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:464)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:436)
	at com.crowsofwar.avatar.common.config.ConfigClient.load(ConfigClient.java:70)
	at com.crowsofwar.avatar.AvatarMod.preInit(AvatarMod.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.crowsofwar.avatar.snakeyaml.error.YAMLException: Class not found: com.crowsofwar.avatar.config.ConfigClient$ActiveBendingSettings
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:642)
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:300)
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
	... 57 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 835713120 bytes (796 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 27 mods loaded, 27 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version      | Source                                           | Signature                                |
	|:----- |:--------------------- |:------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2       | minecraft.jar                                    | None                                     |
	| LCH   | mcp                   | 9.42         | minecraft.jar                                    | None                                     |
	| LCH   | FML                   | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy     | 1.0.0        | minecraft.jar                                    | None                                     |
	| LCH   | xaerominimap_core     | 1.12.2-1.0   | minecraft.jar                                    | None                                     |
	| LCH   | gorecore              | 1.12.2-0.4.5 | avatarmod-1.5.17-alpha.jar                       | None                                     |
	| LCE   | avatarmod             | 1.5.17-alpha | avatarmod-1.5.17-alpha.jar                       | None                                     |
	| LC    | biomesoplenty         | 7.0.1.2443   | BiomesOPlenty-1.12.2-7.0.1.2443-universal.jar    | None                                     |
	| LC    | chiselsandbits        | 14.33        | chiselsandbits-14.33.jar                         | None                                     |
	| LC    | cosmeticarmorreworked | 1.12.2-v5a   | CosmeticArmorReworked-1.12.2-v5a.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LC    | creativecore          | 1.10.0       | CreativeCore_v1.10.34_mc1.12.2.jar               | None                                     |
	| LC    | dragonmounts          | 1.12.2-1.6.3 | DragonMounts2-1.12.2-1.6.3.jar                   | None                                     |
	| LC    | mocreatures           | 12.0.5       | DrZharks+MoCreatures+Mod-12.0.5.jar              | None                                     |
	| LC    | fairylights           | 2.1.10       | fairylights-2.2.0-1.12.2.jar                     | None                                     |
	| LC    | ichunutil             | 7.2.2        | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | hats                  | 7.1.1        | Hats-1.12.2-7.1.1.jar                            | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | hatstands             | 1.0.0        | hatstands-1.0.0-1.12.2.jar                       | None                                     |
	| LC    | jei                   | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar                        | None                                     |
	| LC    | moremobss             | 1.0.0        | More+Mobs+1.12.2.jar                             | None                                     |
	| LC    | morph                 | 7.2.0        | Morph-1.12.2-7.2.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | opframe               | 1.4.0        | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar          | None                                     |
	| LC    | additionalstructures  | 2.3.1        | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
	| LC    | sparkshammers         | @VERSION@    | sparkshammers-1.12.2-1.9.2.jar                   | None                                     |
	| LC    | torohealthmod         | 1.12.2-11    | torohealth-1.12.2-11.jar                         | None                                     |
	| LC    | treechopper           | 1.2.4        | TreeChopper-1.12.2-1.2.4.jar                     | None                                     |
	| LC    | xaerominimap          | 20.27.3      | Xaeros_Minimap_20.27.3_Forge_1.12.jar            | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_20.27.3_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13506 Compatibility Profile Context 23.20.15016.15' Renderer: 'AMD Radeon(TM) R4 Graphics'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13506 Compatibility Profile Context 23.20.15016.15
	OpenGlRenderer: AMD Radeon(TM) R4 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by InvadedDev** [comment]
Does the same thing to me

**Comment by FavouriteDragon** [comment]
Delete your config.
