### ISSUE TITLE
Water Arc crashes my game

### ISSUE THREAD

**Issue by dgdoane** [ProjectKorra/AvatarMod#275]
Crash report
Time: 2/6/22 3:01 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.crowsofwar.avatar.network.AvatarClientProxy.createParticle(AvatarClientProxy.java:135)
	at com.crowsofwar.avatar.client.particle.ParticleBuilder.spawn(ParticleBuilder.java:1039)
	at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.waterArc(WaterBubbleBehavior.java:637)
	at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.onUpdate(WaterBubbleBehavior.java:662)
	at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.onUpdate(WaterBubbleBehavior.java:606)
	at com.crowsofwar.avatar.entity.EntityOffensive.func_70071_h_(EntityOffensive.java:371)
	at com.crowsofwar.avatar.entity.EntityArc.func_70071_h_(EntityArc.java:87)
	at com.crowsofwar.avatar.entity.EntityWaterBubble.func_70071_h_(EntityWaterBubble.java:193)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.crowsofwar.avatar.network.AvatarClientProxy.createParticle(AvatarClientProxy.java:135)
	at com.crowsofwar.avatar.client.particle.ParticleBuilder.spawn(ParticleBuilder.java:1039)
	at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.waterArc(WaterBubbleBehavior.java:637)
	at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.onUpdate(WaterBubbleBehavior.java:662)
	at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.onUpdate(WaterBubbleBehavior.java:606)
	at com.crowsofwar.avatar.entity.EntityOffensive.func_70071_h_(EntityOffensive.java:371)
	at com.crowsofwar.avatar.entity.EntityArc.func_70071_h_(EntityArc.java:87)
	at com.crowsofwar.avatar.entity.EntityWaterBubble.func_70071_h_(EntityWaterBubble.java:193)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: avatarmod:waterbubble (com.crowsofwar.avatar.entity.EntityWaterBubble)
	Entity ID: 7867
	Entity Name: entity.WaterBubble.name
	Entity's Exact location: 208.62, 72.48, 121.15
	Entity's Block location: World: (208,72,121), Chunk: (at 0,4,9 in 13,7; contains blocks 208,0,112 to 223,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.90, -0.04, 0.38
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['dgdoane'/4068, l='MpServer', x=212.50, y=72.00, z=119.50]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (216,64,120), Chunk: (at 8,4,8 in 13,7; contains blocks 208,0,112 to 223,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 481 game time, 481 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 80 total; [EntityPlayerSP['dgdoane'/4068, l='MpServer', x=212.50, y=72.00, z=119.50], EntityBat['Bat'/7304, l='MpServer', x=274.37, y=22.92, z=95.73], EntityBat['Bat'/6340, l='MpServer', x=231.33, y=21.17, z=128.65], EntityBat['Bat'/6341, l='MpServer', x=237.75, y=19.07, z=112.68], EntityZombie['Zombie'/6451, l='MpServer', x=268.50, y=74.00, z=151.50], EntityBat['Bat'/7475, l='MpServer', x=139.59, y=13.37, z=76.49], EntityBat['Bat'/7479, l='MpServer', x=195.61, y=64.92, z=192.07], EntityCreeper['Creeper'/6467, l='MpServer', x=145.50, y=28.00, z=71.50], EntityBat['Bat'/6474, l='MpServer', x=242.58, y=19.03, z=173.51], EntityPiranha['Piranha'/6476, l='MpServer', x=152.50, y=56.00, z=100.50], EntitySquid['Squid'/6477, l='MpServer', x=149.24, y=57.00, z=93.37], EntityBat['Bat'/7512, l='MpServer', x=153.38, y=17.63, z=107.80], EntityBat['Bat'/7514, l='MpServer', x=133.51, y=21.53, z=81.21], EntityZombie['Zombie'/7529, l='MpServer', x=222.49, y=24.00, z=184.22], EntityCreeper['Creeper'/7531, l='MpServer', x=223.50, y=23.00, z=178.50], EntityCreeper['Creeper'/7559, l='MpServer', x=263.50, y=23.00, z=43.50], EntitySkeleton['Skeleton'/7603, l='MpServer', x=141.50, y=39.00, z=82.50], EntitySkeleton['Skeleton'/7617, l='MpServer', x=155.72, y=26.00, z=86.47], EntityZombie['Zombie'/7618, l='MpServer', x=154.50, y=25.00, z=77.50], EntityPig['Pig'/3544, l='MpServer', x=149.50, y=64.00, z=188.50], EntityPig['Pig'/3545, l='MpServer', x=148.50, y=64.00, z=188.50], EntityPig['Pig'/3546, l='MpServer', x=148.34, y=64.00, z=194.27], EntityPig['Pig'/3547, l='MpServer', x=150.25, y=63.00, z=184.47], EntityCreeper['Creeper'/7643, l='MpServer', x=192.50, y=16.00, z=135.50], EntityPig['Pig'/3569, l='MpServer', x=174.50, y=67.00, z=48.50], EntityPig['Pig'/3570, l='MpServer', x=176.50, y=65.00, z=49.45], EntityPig['Pig'/3571, l='MpServer', x=176.50, y=64.00, z=51.64], EntityPig['Pig'/3572, l='MpServer', x=176.50, y=64.00, z=50.45], EntityZombie['Zombie'/7669, l='MpServer', x=175.50, y=27.00, z=146.50], EntityBat['Bat'/6648, l='MpServer', x=283.74, y=20.19, z=105.25], EntityBat['Bat'/6651, l='MpServer', x=189.67, y=15.10, z=125.84], EntityBat['Bat'/6656, l='MpServer', x=228.33, y=44.64, z=77.09], EntitySquid['Squid'/6657, l='MpServer', x=188.60, y=56.48, z=134.81], EntityCreeper['Creeper'/7700, l='MpServer', x=169.50, y=14.00, z=53.50], EntityMimic['Mimic'/7705, l='MpServer', x=225.66, y=32.29, z=140.45], EntityMimic['Mimic'/7706, l='MpServer', x=232.55, y=32.29, z=144.55], EntityMimic['Mimic'/7707, l='MpServer', x=231.55, y=32.29, z=141.45], EntitySkeleton['Skeleton'/7708, l='MpServer', x=227.50, y=32.00, z=140.50], EntitySkeleton['Skeleton'/7715, l='MpServer', x=256.50, y=17.00, z=182.50], EntitySkeleton['Skeleton'/7716, l='MpServer', x=260.50, y=17.00, z=183.50], EntityAnthermite['Anthermite'/3624, l='MpServer', x=261.50, y=91.00, z=48.50], EntityAnthermite['Anthermite'/3625, l='MpServer', x=258.50, y=90.00, z=49.50], EntitySheep['Sheep'/3629, l='MpServer', x=256.21, y=92.00, z=47.25], EntitySheep['Sheep'/3630, l='MpServer', x=249.55, y=91.00, z=40.50], EntitySheep['Sheep'/3631, l='MpServer', x=249.55, y=91.00, z=40.50], EntityItem['item.tile.mushroom'/3632, l='MpServer', x=259.42, y=14.00, z=70.75], EntityZombie['Zombie'/6709, l='MpServer', x=215.50, y=23.00, z=193.50], EntitySpider['Spider'/6712, l='MpServer', x=214.50, y=23.00, z=191.50], EntityCreeper['Creeper'/7745, l='MpServer', x=263.50, y=62.00, z=74.50], EntitySkeleton['Skeleton'/7746, l='MpServer', x=262.50, y=62.00, z=76.50], EntitySkeleton['Skeleton'/7747, l='MpServer', x=260.56, y=62.00, z=71.74], EntityAnthermite['Anthermite'/3652, l='MpServer', x=275.50, y=75.00, z=102.50], EntityAnthermite['Anthermite'/3654, l='MpServer', x=275.50, y=76.00, z=100.50], EntityAnthermite['Anthermite'/3655, l='MpServer', x=278.50, y=75.00, z=99.50], EntityPiranha['Piranha'/6736, l='MpServer', x=187.50, y=56.00, z=160.50], EntityPiranha['Piranha'/6737, l='MpServer', x=180.40, y=55.00, z=151.66], EntityPiranha['Piranha'/6738, l='MpServer', x=187.50, y=56.00, z=158.50], EntityPiranha['Piranha'/6739, l='MpServer', x=117.51, y=61.00, z=38.95], EntityPiranha['Piranha'/6742, l='MpServer', x=117.50, y=60.00, z=40.50], EntityZombieVillager['Zombie Villager'/6752, l='MpServer', x=139.50, y=25.00, z=65.50], EntityZombie['Zombie'/6754, l='MpServer', x=137.50, y=25.00, z=68.79], EntityZombie['Zombie'/6755, l='MpServer', x=132.50, y=25.00, z=78.50], EntitySkeleton['Skeleton'/7782, l='MpServer', x=199.50, y=62.00, z=188.67], EntitySkeleton['Skeleton'/7787, l='MpServer', x=225.50, y=17.00, z=187.50], EntityPiranha['Piranha'/6768, l='MpServer', x=169.50, y=57.00, z=197.50], EntitySquid['Squid'/6770, l='MpServer', x=188.60, y=57.91, z=150.05], EntitySquid['Squid'/6771, l='MpServer', x=181.62, y=56.47, z=157.37], EntitySquid['Squid'/6772, l='MpServer', x=185.98, y=56.00, z=146.25], EntitySpider['Spider'/7813, l='MpServer', x=200.50, y=25.00, z=195.50], EntityCreeper['Creeper'/7815, l='MpServer', x=198.50, y=25.00, z=196.50], EntityZombie['Zombie'/7818, l='MpServer', x=252.50, y=33.00, z=133.50], EntityZombie['Zombie'/7838, l='MpServer', x=193.48, y=13.00, z=192.24], EntitySkeleton['Skeleton'/7850, l='MpServer', x=219.50, y=45.00, z=62.50], EntitySkeleton['Skeleton'/7851, l='MpServer', x=219.50, y=50.00, z=55.73], EntitySpider['Spider'/7855, l='MpServer', x=258.50, y=28.00, z=158.50], EntityWaterBubble['entity.WaterBubble.name'/7867, l='MpServer', x=208.62, y=72.48, z=121.15], EntityItem['item.tile.sand.default'/6847, l='MpServer', x=233.78, y=56.00, z=104.35], EntityItem['item.tile.sand.default'/6848, l='MpServer', x=232.28, y=56.00, z=104.13], EntityItem['item.tile.sand.default'/6849, l='MpServer', x=233.49, y=56.00, z=105.31], EntitySkeleton['Skeleton'/6019, l='MpServer', x=176.50, y=14.00, z=40.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 468683560 bytes (446 MB) / 1174405120 bytes (1120 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 9, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                           | Version      | Source                                                      | Signature                                |
	|:------ |:---------------------------- |:------------ |:----------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                    | 1.12.2       | minecraft.jar                                               | None                                     |
	| LCHIJA | mcp                          | 9.42         | minecraft.jar                                               | None                                     |
	| LCHIJA | FML                          | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                        | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar                               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | am                           | 1.0          | Avatar+Armory+Mod+v1.1.3.jar                                | None                                     |
	| LCHIJA | gorecore                     | 1.12.2-0.4.5 | avatarmod-1.6.0-beta.2.jar                                  | None                                     |
	| LCHIJA | avatarmod                    | 1.6.0-beta.2 | avatarmod-1.6.0-beta.2.jar                                  | None                                     |
	| LCHIJA | dungeonsmod                  | @VERSION@    | DungeonsMod-1.12.2-1.0.8.jar                                | None                                     |
	| LCHIJA | gottschcore                  | 1.14.1       | GottschCore-mc1.12.2-f14.23.5.2854-v1.14.1.jar              | None                                     |
	| LCHIJA | jei                          | 4.16.1.302   | jei_1.12.2-4.16.1.302.jar                                   | None                                     |
	| LCHIJA | journeymap                   | 1.12.2-5.7.1 | journeymap-1.12.2-5.7.1.jar                                 | None                                     |
	| LCHIJA | treasure2                    | 1.18.0       | Treasure2-mc1.12.2-f14.23.5.2859-v1.18.0.jar                | None                                     |
	| LCHIJA | twilightforest               | 3.11.1021    | twilightforest-1.12.2-3.11.1021-universal.jar               | None                                     |
	| LCHIJA | treasure2_twilight_forest_lp | 1.0.0        | Treasure2TwilightForestLP-mc1.12.2-f14.23.5.2854-v1.0.0.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.86' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

**Comment by Noriall** [comment]
i also have this crash

**Comment by Noriall** [comment]
damn i am appreciating so much water bending, i hope i will soon work
