### ISSUE TITLE
Flamethrower crashes server

### ISSUE THREAD

**Issue by JohnB17** [ProjectKorra/AvatarMod#279]
The server crashed and my friend (he is a firebender on the server) he said he used the "flamethrower" ability when it crashed. This is the crash message:
```
[14:16:22 ERROR]: Encountered an unexpected exception
 java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
        at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.waterArc(WaterBubbleBehavior.java:635) ~[WaterBubbleBehavior$Lobbed.class:?]
        at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.onUpdate(WaterBubbleBehavior.java:662) ~[WaterBubbleBehavior$Lobbed.class:?]
        at com.crowsofwar.avatar.entity.data.WaterBubbleBehavior$Lobbed.onUpdate(WaterBubbleBehavior.java:606) ~[WaterBubbleBehavior$Lobbed.class:?]
        at com.crowsofwar.avatar.entity.EntityOffensive.func_70071_h_(EntityOffensive.java:371) ~[EntityOffensive.class:?]
        at com.crowsofwar.avatar.entity.EntityArc.func_70071_h_(EntityArc.java:87) ~[EntityArc.class:?]
        at com.crowsofwar.avatar.entity.EntityWaterBubble.func_70071_h_(EntityWaterBubble.java:193) ~[EntityWaterBubble.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2403) ~[amu.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2354) ~[amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2138) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:744) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:897) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 15 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@214e93d2 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:264) ~[server.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 15 more
Caused by: java.lang.RuntimeException: Attempted to load class btf for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:60) ~[server.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[server.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 15 more
```

**Comment by mahtaran** [comment]
Hi. If you could provide the following information, it'd be helpful:
- Server Java version
- Mod version
- Whether your server is set to online or offline ("cracked") mode
- The server log

Without this information, the best I can do is tell you to ensure you have the latest version of the mod and to delete your config.
