### ISSUE TITLE
Crashing upon loading the mod (Code: -1)

### ISSUE THREAD

**Issue by DamienTheGoat** [ProjectKorra/AvatarMod#289]
Crash report is below, but I will give slight context. Every version after 1.5.17-alpha gives this exact crash report. I have tried loading the mod by itself aswell, but the same thing occured the other mods installed. Once the game is loading the mods, it crashes as soon as the avatar mod is supposed to load.

I notice that the report mentions something about the FoamFix Core mod's config, but I'm still not sure what its saying. I spent a while looking for someone who has the same problem, but not many people do. The ones that do, they don't have any replies or anything. 
Another thing to mention, I have tried this both with and without Optifine enabled (as I had it on), with the result being the same.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  wings (wings-1.1.6-1.12.2.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 9/15/22 1:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Avatar Mod: Out of the Iceberg (avatarmod)
Caused by: Can't construct a java object for tag:yaml.org,2002:com.crowsofwar.avatar.common.config.ConfigClient$ActiveBendingSettings; exception=Class not found: com.crowsofwar.avatar.common.config.ConfigClient$ActiveBendingSettings
 in 'string', line 3, column 24:
    activeBendingSettings: !!com.crowsofwar.avatar.common.c ... 
                           ^

	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:314)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453)
	at com.crowsofwar.avatar.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434)
	at com.crowsofwar.avatar.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
	at com.crowsofwar.avatar.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
	at com.crowsofwar.avatar.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at com.crowsofwar.avatar.snakeyaml.Yaml.load(Yaml.java:437)
	at com.crowsofwar.gorecore.config.ConfigLoader.loadMap(ConfigLoader.java:406)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:466)
	at com.crowsofwar.gorecore.config.ConfigLoader.load(ConfigLoader.java:438)
	at com.crowsofwar.avatar.config.ConfigClient.load(ConfigClient.java:67)
	at com.crowsofwar.avatar.AvatarMod.preInit(AvatarMod.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: com.crowsofwar.avatar.snakeyaml.error.YAMLException: Class not found: com.crowsofwar.avatar.common.config.ConfigClient$ActiveBendingSettings
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:642)
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:300)
	at com.crowsofwar.avatar.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
	... 57 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 439184320 bytes (418 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 54 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version               | Source                                        | Signature                                |
	|:----- |:-------------------------------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2                | minecraft.jar                                 | None                                     |
	| LCH   | mcp                                          | 9.42                  | minecraft.jar                                 | None                                     |
	| LCH   | FML                                          | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                       | minecraft.jar                                 | None                                     |
	| LCH   | foamfixcore                                  | 7.7.4                 | minecraft.jar                                 | None                                     |
	| LCH   | codechickenlib                               | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ancientwarfare                               | 1.12.2-2.7.0.772      | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | ancientwarfareautomation                     | 1.12.2-2.7.0.772      | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | ancientwarfarenpc                            | 1.12.2-2.7.0.772      | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | ancientwarfarestructure                      | 1.12.2-2.7.0.772      | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | ancientwarfarevehicle                        | 1.12.2-2.7.0.772      | ancientwarfare-1.12.2-2.7.0.772.jar           | None                                     |
	| LCH   | antiqueatlas                                 | 4.6.3                 | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
	| LCH   | antiqueatlasoverlay                          | 1.2                   | antiqueatlas-1.12.2-4.6.3.jar                 | None                                     |
	| LCH   | jei                                          | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCH   | appleskin                                    | 1.0.14                | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCH   | waystones                                    | 4.1.0                 | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCH   | atlasextras                                  | 1.8                   | AtlasExtras-1.12.2-1.8.jar                    | None                                     |
	| LCH   | am                                           | 1.0                   | Avatar Armory AddOn Mod v1.1.2.jar            | None                                     |
	| LCH   | llibrary                                     | 1.7.20                | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | alm                                          | 1.1                   | AvatarFlyingLemur-1.12.2-1.1.jar              | None                                     |
	| LCH   | gorecore                                     | 1.12.2-0.4.5          | avatarmod-1.6.2.jar                           | None                                     |
	| LCE   | avatarmod                                    | 1.6.2                 | avatarmod-1.6.2.jar                           | None                                     |
	| LC    | betterburning                                | 0.9.2                 | BetterBurning-1.12.2-0.9.2.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | ctm                                          | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
	| LC    | chisel                                       | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LC    | clumps                                       | 3.1.2                 | Clumps-3.1.2.jar                              | None                                     |
	| LC    | cosmeticarmorreworked                        | 1.12.2-v5a            | CosmeticArmorReworked-1.12.2-v5a.jar          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LC    | custommainmenu                               | 2.0.9.1               | CustomMainMenu-MC1.12.2-2.0.9.1.jar           | None                                     |
	| LC    | movingworld                                  | 1.12-6.353            | movingworld-1.12-6.353-full.jar               | None                                     |
	| LC    | davincisvessels                              | @DVESSELSVER@         | davincisvessels-1.12-6.340-full.jar           | None                                     |
	| LC    | dynamictrees                                 | 1.12.2-0.9.29         | DynamicTrees-1.12.2-0.9.29.jar                | None                                     |
	| LC    | fastleafdecay                                | v14                   | FastLeafDecay-v14.jar                         | None                                     |
	| LC    | foamfix                                      | 0.10.11-1.12.2        | foamfix-0.10.11-1.12.2.jar                    | None                                     |
	| LC    | grapplemod                                   | 1.12.2-v11.1          | grapplemod-v11.1-1.12.2.jar                   | None                                     |
	| LC    | iceandfire                                   | 1.9.1                 | iceandfire-1.9.1-1.12.2.jar                   | None                                     |
	| LC    | infernalmobs                                 | 1.7.6                 | InfernalMobs-1.12.2.jar                       | None                                     |
	| LC    | kypjci                                       | 1.1                   | JustCopyIt-1.1-beta.jar                       | None                                     |
	| LC    | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LC    | malisisdoors                                 | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LC    | modularvc                                    | 1.1.1                 | ModularVoiceChat-1.1.1.jar                    | None                                     |
	| LC    | mowziesmobs                                  | 1.5.8                 | mowziesmobs-1.5.8.jar                         | None                                     |
	| LC    | multimob                                     | 1.0.5                 | multimob-1.0.5.jar                            | None                                     |
	| LC    | neat                                         | 1.4-17                | Neat 1.4-17.jar                               | None                                     |
	| LC    | overpoweredarmorbar                          | @VERSION@             | overloadedarmorbar-1.0.4g.jar                 | None                                     |
	| LC    | primitivemobs                                | 1.2.3a                | primitivemobs-1.2.3a.jar                      | None                                     |
	| LC    | resourceloader                               | 1.5.3                 | ResourceLoader-MC1.12.1-1.5.3.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | stg                                          | 1.12.2-1.2.3          | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LC    | travelersbackpack                            | 1.0.35                | TravelersBackpack-1.12.2-1.0.35.jar           | None                                     |
	| LC    | wings                                        | 1.1.6                 | wings-1.1.6-1.12.2.jar                        | None                                     |
	| LC    | mowzies_wings                                | 1.0.0                 | wings-1.1.6-1.12.2.jar                        | None                                     |
	| LC    | reauth                                       | 3.6.0                 | reauth-3.6.0.jar                              | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| UD    | bauble_wings                                 | 1.0.0                 | wings-1.1.6-1.12.2.jar                        | None                                     |
	| UD    | mobends_wings                                | 1.0.0                 | wings-1.1.6-1.12.2.jar                        | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.11-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.8729' Renderer: 'Intel(R) UHD Graphics 610'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.8729
	OpenGlRenderer: Intel(R) UHD Graphics 610
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by DamienTheGoat** [comment]
Another thing, The curseforge page says i need forge 2838. and I am using 2860. I know this, but I promise you, I have tried both of those, as well as 2 other versions. Same results. 1.5.17-alpha and everything before works, and every version after that has this same crash report

**Comment by MagicMonsterr** [comment]
Delete the folder called "avatar" in your config folder.
