### ISSUE TITLE
Issue with bungeecord and mod

### ISSUE THREAD

**Issue by skylarcoolya** [ProjectKorra/AvatarMod#29]
So I am trying to use the mod on my bungeecord network well set it up and its giving a error every time I try to use a move if you can fix it would be amazing I might attempt to fix it myself but I'd prefer it to be a official fix for updates that come out on version 1.12.1

![screenshot_1](https://user-images.githubusercontent.com/10287418/31105443-334f38de-a7b2-11e7-85e2-27dc0bb34a86.png)

I was only able to screenshot what it says as it wouldnt allow me to copy and it wasn't in the logs if you need a repeat of the error please feel free to contact me ASAP <3

**Comment by CrowsOfWar** [comment]
Hey thanks for the report. I'll try to see what's happening. If you can get this error to happen again, could you also see if there are more errors before it and post them?

(Btw, you can copy text in cmd by clicking/dragging the mouse to select, then pressing enter)

Thanks

**Comment by skylarcoolya** [comment]
I couldnt get the error to repeat in console but it seems the player log is much better it basically kicks me to the hub after I try to use a move and this is what the client says I added a bit extra just to show nothing else is useful above

[20:12:49] [Netty Client IO #2/INFO]: [Netty Client IO #2] Client side modded connection established
[20:12:49] [main/INFO]: Client fetcher- all player data decached
[20:12:49] [main/INFO]: Mapping halted in F:\Curse\Instances\The Anime Network ~ Avatar\journeymap\data\mp\The~Anime~Network\DIM0
[20:12:49] [main/INFO]: Client fetcher- all player data decached
[20:12:49] [main/WARN]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[20:12:49] [main/WARN]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[20:12:50] [main/INFO]: Loading journeymap.topo.config
[20:12:50] [main/INFO]: Loaded 0 waypoints from F:\Curse\Instances\The Anime Network ~ Avatar\journeymap\data\mp\The~Anime~Network\waypoints
[20:12:50] [main/INFO]: Mapping started in F:\Curse\Instances\The Anime Network ~ Avatar\journeymap\data\mp\The~Anime~Network\DIM0. Memory: 2306MB total, 1768MB free 
[20:12:52] [main/INFO]: [CHAT] MystifiedSky joined the game
[20:12:59] [main/INFO]: [CHAT] The server you were previously on went down, you have been connected to a fallback server
[20:12:59] [main/INFO]: Client fetcher- all player data decached
[20:12:59] [main/INFO]: Mapping halted in F:\Curse\Instances\The Anime Network ~ Avatar\journeymap\data\mp\The~Anime~Network\DIM0
[20:13:00] [main/INFO]: Client fetcher- all player data decached
[20:13:00] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: index: 1, length: 72 (expected: range(0, 71))
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: index: 1, length: 72 (expected: range(0, 71))
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1353) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1348) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.internalNioBuffer(PooledUnsafeDirectByteBuf.java:331) ~[PooledUnsafeDirectByteBuf.class:4.1.9.Final]
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:630) ~[ByteBufUtil.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1213) ~[AbstractByteBuf.class:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.toString(PacketBuffer.java:1289) ~[gy.class:?]
	at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:380) ~[gy.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147240_a(NetHandlerPlayClient.java:1875) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:58) ~[iw.class:?]
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:11) ~[iw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[20:13:00] [main/INFO]: [CHAT] Current Tool: Default Tool

**Comment by skylarcoolya** [comment]
This is the specific part I believe to be the issue

[20:13:00] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: index: 1, length: 72 (expected: range(0, 71))
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: index: 1, length: 72 (expected: range(0, 71))
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1353) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1348) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.internalNioBuffer(PooledUnsafeDirectByteBuf.java:331) ~[PooledUnsafeDirectByteBuf.class:4.1.9.Final]
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:630) ~[ByteBufUtil.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1213) ~[AbstractByteBuf.class:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.toString(PacketBuffer.java:1289) ~[gy.class:?]
	at net.minecraft.network.PacketBuffer.func_150789_c(PacketBuffer.java:380) ~[gy.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147240_a(NetHandlerPlayClient.java:1875) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:58) ~[iw.class:?]
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148833_a(SPacketCustomPayload.java:11) ~[iw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[20:13:00] [main/INFO]: [CHAT] Current Tool: Default Tool

**Comment by CrowsOfWar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BungeeCord issue on Github](https://trello.com/c/4kWLFBTc/286-bungeecord-issue-on-github)

**Comment by FavouriteDragon** [comment]
This is fixed so I'm closing it
