### ISSUE TITLE
Seems a the mcpack.info file is bugging out.

### ISSUE THREAD

**Issue by omegadmm** [ProjectKorra/AvatarMod#37]
Minecraft 1.12.1 with Forge 2485:
[03:48:35] [Server thread/ERROR] [FML]: The mcmod.info file in avatarmod-a4.6.jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65) ~[JsonParser.class:?]
	at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:62) [MetadataCollection.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:58) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:138) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:403) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:543) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:60) ~[JsonParser.class:?]
	... 12 more
[03:48:35] [Server thread/DEBUG] [FML]: Identified a mod of type Lnet/minecraftforge/fml/common/Mod; (com.crowsofwar.avatar.AvatarMod) - loading

**Comment by Zarepheth** [comment]
I'm seeing the same JSON parsing error in my MultiMC logs while launching Minecraft with Avatar installed. Though non-fatal, I still don't like seeing errors (or even warnings) in the logs...

**Comment by CrowsOfWar** [comment]
Thanks for mentioning this. I'll try to get it sorted out

**Comment by CrowsOfWar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix mcmod.info](https://trello.com/c/DWwXOe6g/341-fix-mcmodinfo)

**Comment by omegadmm** [comment]
Seems the link is private. I made an account yet I cannot access the file.

**Comment by CrowsOfWar** [comment]
Yeah it's on the private trello board, I will be fixing it shortly

**Comment by CrowsOfWar** [comment]
Thanks guys, the issue has been resolved, this error will not show up in the next update (a5.0). Should be coming in the next 1-2 weeks.
