### ISSUE TITLE
Crash when mob killed by fake player (Mob grinders)

### ISSUE THREAD

**Issue by Darkveld** [ProjectKorra/AvatarMod#97]
Attempting to use any kind of mob grinder or fake player to get player kill only loot will corrupt the server with an infinite loop of crashes until the offending mob/blocks are deleted in MCEdit:

---- Minecraft Crash Report ----
// I blame Mahtaran, author of Avatar Mod: Out of the Iceberg.

Time: 2018-10-29 09:03:00 MST
Description: Colliding entity with block

java.lang.IllegalArgumentException: Cannot get client player data for null player ID
at com.crowsofwar.gorecore.data.PlayerDataFetcherServer.fetch(PlayerDataFetcherServer.java:50)
at com.crowsofwar.gorecore.data.PlayerDataFetcherSided.fetch(PlayerDataFetcherSided.java:47)
at com.crowsofwar.gorecore.data.PlayerDataFetcher.fetch(PlayerDataFetcher.java:65)
at com.crowsofwar.gorecore.data.PlayerDataFetcher.fetch(PlayerDataFetcher.java:79)
at com.crowsofwar.avatar.common.data.BendingData.get(BendingData.java:83)
at com.crowsofwar.avatar.common.data.ctx.PlayerBender.getData(PlayerBender.java:57)
at com.crowsofwar.avatar.common.bending.fire.StatCtrlInfernoPunch.onInfernoPunch(StatCtrlInfernoPunch.java:133)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_131_StatCtrlInfernoPunch_onInfernoPunch_LivingAttackEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:572)
at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:850)
at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:70)
at net.minecraft.entity.monster.EntityZombie.attackEntityFrom(EntityZombie.java:233)
at com.rwtema.extrautils2.blocks.BlockSpike$SpikeType$3.hurtEntity(BlockSpike.java:241)
at com.rwtema.extrautils2.blocks.BlockSpike.onEntityCollidedWithBlock(BlockSpike.java:165)
at net.minecraft.entity.Entity.doBlockCollisions(Entity.java:1044)
at net.minecraft.entity.Entity.move(Entity.java:964)
at net.minecraft.entity.EntityLivingBase.travel(EntityLivingBase.java:1951)
at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2386)
at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
at net.minecraft.entity.monster.EntityMob.onLivingUpdate(EntityMob.java:45)
at net.minecraft.entity.monster.EntityZombie.onLivingUpdate(EntityZombie.java:223)
at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2172)
at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50)
at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
at net.minecraft.world.World.updateEntity(World.java:1955)
at net.minecraft.world.World.redirect$updateEntity$zzo000(World.java:5117)
at net.minecraft.world.World.updateEntities(World.java:1759)
at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
at java.lang.Thread.run(Unknown Source)

**Comment by FavouriteDragon** [comment]
Oof I'll try and fix that.

**Comment by FavouriteDragon** [comment]
Ok this is fixed and will be in the next release
